defaultContentLanguage = "en"
languageCode = "en"

title = "Gianfranco Demarco"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  avatarURL = "/images/avatar.jpg"
  description = "Data & AI Software Engineer | M.Sc. in Artificial Intelligence"
  showPostsOnHomePage = "popular"
  footer = "Gianfranco Demarco"

  socialIcons = [
    {name = "github", url = "https://github.com/gianfrancodemarco"},
    {name = "linkedin", url = "https://it.linkedin.com/in/gianfranco-demarco-207288175"},
    {name = "email", url = "mailto:gianfrademarco@gmail.com"}
  ]

  projects = [
    {name = "test", url = "www.google.com" }
  ]

  CustomHeadHTML = """
  <link rel="stylesheet" href="/css/main.css">
  <link rel="stylesheet" href="/css/common.css">
  <link rel="stylesheet" href="/css/dark.css">
  """

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/gianfrancodemarco"
    weight = 3
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://it.linkedin.com/in/gianfranco-demarco-207288175"
    weight = 4    
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "email"
    url = "mailto:gianfrademarco@gmail.com"
    weight = 5
    pre = "<span data-feather='at-sign'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 1
    ordered = false